config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    # root route for admin
    root "application#index"
    resources :posts, except: [:index, :show]
    resources :users do
      member do
        patch :archive
      end
    end
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # non-admin routes
  root "posts#index"
  resources :posts, only: [:index, :show] do
    resources :comments
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_one_attached :image
  attr_reader :author

  def thumbnail
    return self.image.variant(resize_to_fill: [100, nil])
  end

  def author
    self.title
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # only show non-archived users
  scope :active, lambda { where(archive_at: nil) }

  def to_s
    "#{email} (#{admin? ? "Admin" : "User"})"
  end

  # archive user, updating/setting archive_at Time
  def archive!
    self.update(archive_at: Time.now)
    # set the current_user archive_at to nil 
    if current_user
      self.archive_at = nil
    end
  end
  # locking out an archived user from signing in
  def active_for_authentication?
    super && archive_at.nil?
  end

  # inactive message override
  def inactive_message
    archive_at.nil? ? super : archived
  end
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  before_action :authorize_admin!

  def index
  end

  private
  def authorize_admin!
    # check if user is logged in
    authenticate_user!

    # check whether the current_user is an admin
    # if current_user.admin?
    #   redirect_to "/admin"
    # else
    #   redirect_to root_path
    #   flash[:notice] = "You are not an admin"
    # end
    # unless block
    unless current_user.admin?
      redirect_to root_path, flash: { alert: "You are not an admin"}
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ApplicationController

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path, flash: { notice: "Post created successfully"}
    else
      render :new
      flash.now[:alert] = "Post not created"
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
      flash.now[:notice] = "Post created successfully"
    else
      render :edit
      flash.now[:alert] = "Post not updated"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to posts_path
      flash.now[:alert] = "Post has been deleted"
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :description, :image)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :archive]

  def index
    @users = User.active.order(:email)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "User has been created"
      redirect_to admin_users_path
    else
      flash[:notice] = "Error prohibited user from creating"
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    # do not update if password is blank
    if params[:user][:password].blank?
      params[:user].delete(:password)
    end

    if @user.update(user_params)
      flash[:notice] = "User has been updated"
      redirect_to admin_users_path
    else
      flash[:notice] = "User not updated"
      render :edit
    end
  end

  def archive
    if @user == current_user
      flash[:alert] = "You cannot archive yourself"
      redirect_to admin_users_path
    else
      @user.archive!
      flash[:notice] = "User has been archived"
      redirect_to admin_users_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :admin)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  def index
    @comments = Comment.all
  end

  def new
    @comment = @post.comments.build
  end

  def create
    @comment = @post.comments.build(comment_params)
    if @comment.save
      # redirect_to post_comment_path(@post, @comment)
      redirect_to post_path(@post)
      flash.now[:notice] = "Comment created successfully"
    else
      render :new
      flash.now[:alert] = "Comment not created"
    end
  end

  def show
    @comment = @post.comments.find(params[:id])
  end

  def edit
    @comment = @post.comments.find(params[:id])
  end

  def update
    @comment = @post.comments.find(params[:id])
    if @comment.update(comment_params)
      redirect_to post_path(@post)
      flash.now[:notice] = "Comment successfully updated"
    else
      render :edit
      flash.now[:alert] = "Comment not updated"
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    if @comment.destroy
      redirect_to post_comment_path(@post, @comment)
      flash[:alert] = "Comment deleted"
    else
      puts "Cannot destroy comment"
    end
  end

  private
  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  private
  def post_params
    params.require(:post).permit(:title, :description, :image)
  end
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def admins_only(&block)
    block.call if current_user.try(:admin?)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/application/index.html.erb
<div class="row">
  <div class="col-md-9">
    <header>
      <h1>Admin Lounge</h1>
    </header>
  </div>
  <div class="col-md-3">
    <h5 class="text-uppercase">Admin Links</h5>
    <%= link_to "Users", admin_users_path %>
  </div>
</div>

app/views/admin/posts/_form.html.erb
<%= form_with(model: [:admin, post], local:true) do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field:title %>
  </div>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field:description %>
  </div>
  <div class="post-image">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <%= form.submit %>
<% end %>

app/views/admin/posts/edit.html.erb
<h2>Edit Post</h2>

<%= render "form", post: @post %>

app/views/admin/posts/new.html.erb
<h1>New Post</h1>

<%= render "form", post: @post %>

app/views/admin/users/_form.html.erb
<!-- new user form-->
<%= form_with(model: [:admin, user], local: true) do |form| %>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
  <div class="form-group">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>
  <div class="form-group">
    <%= form.label :admin %>
    <%= form.check_box :admin, label: "Is an admin?" %>
  </div>

  <%= form.submit %>
<% end %>

app/views/admin/users/edit.html.erb
<header>
  <h3>Edit User</h3>
</header>

<%= render "form", user: @user %>

app/views/admin/users/index.html.erb
<div class="container">
  <header>
    <h3>Users</h3>

    <ul>
      <li><%= link_to "New User", new_admin_user_path %></li>
    </ul>
  </header>

  <% @users.each do |user| %>
    <div class="user-email p-2">
      <ul>
        <li><%= link_to user, [:admin, user] %></li>
        <!-- <li><%= user.email %></li> <strong>Admin: </strong><span><%= user.admin %></span> -->
      </ul>
    </div>
  <% end %>
</div>

app/views/admin/users/new.html.erb
<header>
  <h3>New User</h3>
</header>

<%= render "form", user: @user %> 

app/views/admin/users/show.html.erb
<header>
  <h3><%= @user %></h3>
  <ul>
    <li>
      <%= link_to "Edit User", [:edit, :admin, @user] %>
    </li>
    <li>
      <%= button_to "Archive User", [:archive, :admin, @user], method: :patch, data: { confirm: "Are you sure? "}, class: "btn btn-primary"%>
    </li>
  </ul>
</header>

app/views/comments/_comment.html.erb
<div class="">
  <%= comment.content %>
  <%= time_tag comment.created_at, "data-local": "time-ago" %>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [post, Comment.new], local: true) do |form| %>
  <div class="form-group m-4">
    <div class="d-flex justify-content-start">
      <%= form.label :content, "Your comment, " %>
    </div>
    <div class="">
      <%= form.text_area :content, size: "60x5" %>
    </div>
  </div>

  <div class="d-flex justify-content-end">
      <%= form.submit "Create" %>
  </div>

<% end %>

app/views/comments/edit.html.erb
<h2>Edit Comment</h2>

<%= form_with(model: [@post, @comment], local: true) do |form| %>
  <div class="form-group m-4">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="m-4">
      <%= form.submit %>
  </div>

<% end %>

app/views/comments/index.html.erb
<%# comments#show %>

<div class="">
  <% @comments.each do |comment| %>
    <%= comment.post %>
    <%= comment.id %>
    <%= comment.content %>
  <% end %>
</div>

<%= link_to "comments", post_comments_path %>

app/views/comments/new.html.erb
<h2>New Comment</h2>

<%= render "form", post: @post, comment: @comment %> 

app/views/comments/show.html.erb
<h2>Comment</h2>

<div class="comment">
  <div class="comment-content">
    <%= @comment.content %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="text-center" style="background-color: #749664" >
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2022 Copyright
    <a class="text-dark" href="https://mdbootstrap.com/"></a>
  </div>
  <!-- Copyright -->
</footer>

app/views/layouts/_nav.html.erb
<!-- Navbar -->
<!-- As a link -->
<nav class="navbar container-fluid" style="background-color: #749664">
  <div class="px-2">
    <a class="navbar-brand text-decoration-none" href="/">
      <%= image_tag("icons8-home.svg") %>
    </a>
  </div>
  <div class="pr-4 d-flex justify-content-end">
    <% if user_signed_in? %>
      <span class="px-2 pt-2"><%= current_user.email %></span>
      <span><%= button_to "Sign out", destroy_user_session_url, method: :delete, class: "delete", class: "btn btn-danger mx-2"%></span>
    <% else %>
      <span class="px-2"><%= link_to "Sign in", new_user_session_url, class: "text-decoration-none text-black"%></span>
      <span class="px-2"><%= link_to "Sign up", new_user_registration_url, class: "text-decoration-none text-black"%></span>
    <% end %>
  </div>
</nav>
  <!-- Navbar -->

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ABlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-light bg-faded">
    <div class="row mb-4">
      <%= render "layouts/nav" %>
    </div>
    <div class="row mt-4">
      <div class="notice">
        <p><!-- sign\-in sign_out notice--></p>
        <p><%= notice %></p>
        <p><%= alert %></p>
      </div>
        <%= yield %>
    </div>
    <div class="footer">
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/posts/_comments.html.erb
<h2>Comment</h2>

<%= render "comments/new", post: post %>

app/views/posts/_form.html.erb
<%= form_with(model: post, local:true) do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field:title %>
  </div>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field:description %>
  </div>
  <div class="post-image">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <%= form.submit %>
<% end %>

app/views/posts/_form0.html.erb
<%= form_with(model: [post, Comment.new], local: true) do |form| %>
  <div class="form-group m-4">
    <%# <%= form.label :content %> %>
    <%= form.text_area :content %>
  </div>

  <div class="m-4">
      <%= form.submit %>
  </div>

<% end %>

app/views/posts/hold.html.erb
<div class="">
  <div class="row">
    <div class="text-center post-img">
      <% if @post.image.attached? %>
        <%= image_tag(@post.image, width: "100%", height: "500px") %>
      <% end %>
    </div>
  </div>
  <div class=" pt-4 text-center post-title">
    <h2><%= @post.title %></h2>
  </div>
  <div class="row">
    <div class="col">
      <div class="d-flex justify-content,center">
        <div class="shadow-sm mt-4 mb-4 bg-white text-center pt-4", style="width: 50%">
          <p><%= @post.description %></p>
        </div>
      </div>
      <div class="post-links">
        <!-- edit post -->
        <div class="edit-post">
          <%= link_to "Edit Post", edit_post_path %>
        </div>

        <!-- delete post -->
        <div class="delete-post">
          <%= link_to "Delete Post", post_path(@post), method: :delete, data: {confirm: "Are you sure?"} %>
        </div>

        <!-- posts-path -->
        <!-- <div class="posts-path">
          <%= link_to 'posts', posts_path %>
        </div> -->
      </div>
    </div>
  </div>
  <div class="row">
    <!-- comment partial -->
    <div class="p-4 mt-4 pt-" style="width: "500px">
      <div class="render-comment-form">
        <!-- render comment partial -->
        <%= render "comments/form", post: @post %>
      </div>
    </div>
  </div>
  <div class="row justify-content-start">
    <div class="col-6 shadow-sm p-4 bg-white">
      <div class="text-center post-comments">
        <h3>Comments</h3>
        <div class="p-2 m-2 render-post-comments">
          <% @post.comments.each do |comment| %>
            <div class="comment-content border-bottom-2">
              <%= comment.content %>
              <ul>
                <!-- <li><%= link_to "Show", post_comment_path(@post, comment) %></li> -->
                <p>Posted <%= time_tag comment.created_at, "data-local": "time-ago" %></p>
                <!-- edited at-->
                <% if comment.created_at == comment.updated_at? %>
                  <p>do not display</p>
                  <% else %>
                  <p>Edited <%= time_tag comment.updated_at, "data-local": "time-ago" %></p>
                <% end %>
                <%= link_to "Edit", edit_post_comment_path(@post, comment), class: "m-4 btn btn-success" %>
                <%= link_to "Delete", post_comment_path(@post, comment), method: :destroy, class: "btn btn-danger" %>
              </ul>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<main>
  <div class="container">
    <div class="row d-flex mx-auto justify-content-center mt-4">
      <div class="bg-image hover-overlay ripple shadow-2-strong rounded-5" data-mdb-ripple-color="light">
        <img src="https://mdbootstrap.com/img/new/slides/031.jpg" class="img-fluid" />
        <a href="#!">
          <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
        </a>
      </div>
      <div class="row">
        <div class="col d-flex justify-content-start pt-4">
          <h4><strong>Just a blog</strong></h4>
        </div>
        <!-- new post path -->
        <div class="new-post">
          <% admins_only do %>
            <ul class="actions">
              <%= link_to "Admin", admin_root_path %>
              <li><%= link_to "New Post", new_admin_post_path, class: "new" %></li>
            </ul>
          <% end %>

        </div>
      </div>
    </div>
    <hr class="mb-4"/>
    <!-- iterate thru the block -->
    <div class="row">
      <div class="col-8 mx-auto">
        <% @posts.each do |post| %>
          <div class="card my-4">
            <div class="row">
              <div class="col">
                <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light" >
                  <% if post.image.attached? %>
                    <div class="img-fluid">
                      <%= image_tag(post.image, width: "50%", height: "50%") %>
                    </div>
                  <% else %>
                    <p>No image attached</p>
                  <% end %>
                </div>
              </div>
              <div class="col">
                <div class="d-flex justify-content-start">
                  <div class="py-2">
                    <h4><%= link_to post.title, post, class: "text-decoration-none text-black" %></h4>
                  </div>
                </div>
                <div class="py-2">
                  <p><%= truncate post.description %></p>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_with(model: @post, local:true) do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <%= form.submit "Create Post" %>
<% end %>

app/views/posts/show.html.erb
<main>
  <div class="container">
    <section class="text-center">
      <div class="card bg-white mb-4">
        <div class="row">
          <div class="col">
            <strong><h3 class="text-center p-4"><%= @post.title %></h3></strong>
          </div>
        </div>
        <!-- image -->
        <div class="row">
          <div class="rounded post-img mb-4">
            <% if @post.image.attached? %>
              <%= image_tag(@post.image, width: "65%", height: "400px") %>
            <% else %>
              <p>No image attached</p>
            <% end %>
          </div>
        </div>
        <!-- card body -->
        <div class="card-body">
          <hr>
          <!-- grid layout -->
          <div class="row">
            <div class="col-8 pt-4 pb-4">
              <div class="container">
                <div class="row">
                  <div class="col">
                    <div class="d-flex justify-content-start">
                      <strong class="ml-2">Published <span class="font-italic"><%= time_tag @post.created_at, "data-local": "time-ago" %></span></strong>
                    </div>
                    <!-- admins_only -->
                    <% admins_only do %>
                      <ul class="actions">
                        <!-- edit post -->
                        <span><%= link_to "Edit Post", edit_admin_post_path(@post), class: "btn btn-primary m-2" %></span>
                        <span><%= button_to "Delete Post", admin_post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %></span>
                      </ul>
                    <% end %>
                    <div class="p-4 text-monospace">
                      <p>African tech talent startup, TalentQL, has today, October 21, 2021, launched AltSchool Africa. The programme is the startup’s latest attempt to create a tech talent pipeline following the launch of Pipeline, it’s mentorship and upskilling program for senior developers.</p>
                    </div>
                  </div>
                </div>
                <!-- render comment form -->
                <div class="row">
                  <div class="col">
                    <div class="d-flex justify-content-start">
                      <%= render "comments/form", post: @post, width: "100%" %>
                    </div>
                  </div>
                </div>
                <!-- comments count -->
                <div class="row">
                  <div class="col">
                    <div class="d-flex justify-content-start">
                      <p class="px-4"><%= @post.comments.count %><strong class="px-2">Comments</strong></p>
                      <!-- <span><%= link_to "New Comment", new_post_comment_path(@post) %></span> -->
                    </div>
                  </div>
                </div>
                <!-- render comments -->
                <div class="row">
                  <div class="col">
                    <% @post.comments.each do |comment| %>
                      <div class="d-flex justify-content-start px-4 mx-4">
                        <div class="d-dlex flex-column py-2">
                          <%= comment.content %>
                          <span><%= button_to "Delete", post_comment_path(@post, comment), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-danger"%></span>
                          <span><%= link_to "Edit", edit_post_comment_path(@post, comment) %></span>
                          <div class="">
                            <span><strong>Posted by <span>user </span><%= time_tag comment.created_at, "data-local": "time-ago"%></strong></span>
                          </div>
                        </div>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-4 pt-4 pb-4">
              <div class="container">
                <div class="row">
                  <div class="col">
                    <div class="d-flex justify-content-start">
                      <strong>Editor`s pick <span></span></strong>
                    </div>
                    <div class="p-4">
                      <p>As Africa’s tech ecosystem has grown, a number of organizations have sprung up to supply tech talent for startups. After an initial focus on building entry-level talent led by the likes of Andela, the demand for senior talent meant that for a while, training entry-level engineers took a backseat.</p>
                    </div>
                    <!-- author -->
                    <div class="card">
                      <div class="row">
                        <div class="d-flex justify-content-center pt-2">
                          <h5>About</h5>
                        </div>
                      </div>
                      <div class="row">
                        <div class="p-2 d-flex justify-content-center">
                          <p>image goes here</p>
                        </div>
                      </div>
                      <div class="row">
                        <div class="px-4 d-flex justify-content-start">
                          <p class="text-muted">
                            Hey, my name is Alphan Kihara and I love Ruby.
                            This blog aims to walk with you through my journey of web development.
                            Here I document technologies as I learn them.
                            For any support or enquiries, hit me up on my socials, Thanks.
                          </p>
                        </div>
                      </div>
                      <div class="row">
                        <div class="px-2 pb-4 d-flex justify-content-center">
                          socials links go here
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</main>